name: brand_forge_example
description: An example project for the brand_forge package.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  brand_forge:
    path: ../ # Relative path to the root of your brand_forge package
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
